name: smartpacifier_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  # gRPC client/server stubs
  grpc: ^4.0.1

  # Protocol Buffers runtime
  protobuf: ^4.0.0
  protobuf_google: ^1.0.0
  yaml: ^3.1.0

  # Flutter SDK itself
  flutter:
    sdk: flutter

  # Charting library (Git master now removes boldTextOverride)
  fl_chart:
    git:
      url: https://github.com/imaNNeo/fl_chart.git
      ref: main

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  # Flutter’s built-in test framework
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter projects.
  flutter_lints: ^5.0.0

  # Protoc plugin for generating Dart code
  protoc_builder: ^0.4.1
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - lib/screens/settings/configuration/config.yml
