// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: myservice.proto

#include "myservice.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace myservice {
PROTOBUF_CONSTEXPR PayloadMessage::PayloadMessage(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PayloadMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PayloadMessageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PayloadMessageDefaultTypeInternal() {}
  union {
    PayloadMessage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PayloadMessageDefaultTypeInternal _PayloadMessage_default_instance_;
}  // namespace myservice
static ::_pb::Metadata file_level_metadata_myservice_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_myservice_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_myservice_2eproto = nullptr;

const uint32_t TableStruct_myservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::myservice::PayloadMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::myservice::PayloadMessage, _impl_.data_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::myservice::PayloadMessage)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::myservice::_PayloadMessage_default_instance_._instance,
};

const char descriptor_table_protodef_myservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017myservice.proto\022\tmyservice\032\033google/pro"
  "tobuf/empty.proto\"\036\n\016PayloadMessage\022\014\n\004d"
  "ata\030\001 \001(\0142R\n\tMyService\022E\n\016StreamMessages"
  "\022\026.google.protobuf.Empty\032\031.myservice.Pay"
  "loadMessage0\001b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_myservice_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::_pbi::once_flag descriptor_table_myservice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_myservice_2eproto = {
    false, false, 181, descriptor_table_protodef_myservice_2eproto,
    "myservice.proto",
    &descriptor_table_myservice_2eproto_once, descriptor_table_myservice_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_myservice_2eproto::offsets,
    file_level_metadata_myservice_2eproto, file_level_enum_descriptors_myservice_2eproto,
    file_level_service_descriptors_myservice_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_myservice_2eproto_getter() {
  return &descriptor_table_myservice_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_myservice_2eproto(&descriptor_table_myservice_2eproto);
namespace myservice {

// ===================================================================

class PayloadMessage::_Internal {
 public:
};

PayloadMessage::PayloadMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:myservice.PayloadMessage)
}
PayloadMessage::PayloadMessage(const PayloadMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PayloadMessage* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_data().empty()) {
    _this->_impl_.data_.Set(from._internal_data(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:myservice.PayloadMessage)
}

inline void PayloadMessage::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PayloadMessage::~PayloadMessage() {
  // @@protoc_insertion_point(destructor:myservice.PayloadMessage)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PayloadMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.data_.Destroy();
}

void PayloadMessage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PayloadMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:myservice.PayloadMessage)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PayloadMessage::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes data = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PayloadMessage::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:myservice.PayloadMessage)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes data = 1;
  if (!this->_internal_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:myservice.PayloadMessage)
  return target;
}

size_t PayloadMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:myservice.PayloadMessage)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes data = 1;
  if (!this->_internal_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_data());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PayloadMessage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PayloadMessage::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PayloadMessage::GetClassData() const { return &_class_data_; }


void PayloadMessage::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PayloadMessage*>(&to_msg);
  auto& from = static_cast<const PayloadMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:myservice.PayloadMessage)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PayloadMessage::CopyFrom(const PayloadMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:myservice.PayloadMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PayloadMessage::IsInitialized() const {
  return true;
}

void PayloadMessage::InternalSwap(PayloadMessage* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.data_, lhs_arena,
      &other->_impl_.data_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata PayloadMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_myservice_2eproto_getter, &descriptor_table_myservice_2eproto_once,
      file_level_metadata_myservice_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace myservice
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::myservice::PayloadMessage*
Arena::CreateMaybeMessage< ::myservice::PayloadMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::myservice::PayloadMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
