// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: myservice.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_myservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_myservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/empty.pb.h>
#include "sensor_data.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_myservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_myservice_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_myservice_2eproto;
namespace myservice {
class PayloadMessage;
struct PayloadMessageDefaultTypeInternal;
extern PayloadMessageDefaultTypeInternal _PayloadMessage_default_instance_;
}  // namespace myservice
PROTOBUF_NAMESPACE_OPEN
template<> ::myservice::PayloadMessage* Arena::CreateMaybeMessage<::myservice::PayloadMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace myservice {

// ===================================================================

class PayloadMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:myservice.PayloadMessage) */ {
 public:
  inline PayloadMessage() : PayloadMessage(nullptr) {}
  ~PayloadMessage() override;
  explicit PROTOBUF_CONSTEXPR PayloadMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PayloadMessage(const PayloadMessage& from);
  PayloadMessage(PayloadMessage&& from) noexcept
    : PayloadMessage() {
    *this = ::std::move(from);
  }

  inline PayloadMessage& operator=(const PayloadMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline PayloadMessage& operator=(PayloadMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PayloadMessage& default_instance() {
    return *internal_default_instance();
  }
  enum PayloadCase {
    kSensorData = 1,
    PAYLOAD_NOT_SET = 0,
  };

  static inline const PayloadMessage* internal_default_instance() {
    return reinterpret_cast<const PayloadMessage*>(
               &_PayloadMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PayloadMessage& a, PayloadMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(PayloadMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PayloadMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PayloadMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PayloadMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PayloadMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PayloadMessage& from) {
    PayloadMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PayloadMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "myservice.PayloadMessage";
  }
  protected:
  explicit PayloadMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSensorDataFieldNumber = 1,
  };
  // .Protos.SensorData sensor_data = 1;
  bool has_sensor_data() const;
  private:
  bool _internal_has_sensor_data() const;
  public:
  void clear_sensor_data();
  const ::Protos::SensorData& sensor_data() const;
  PROTOBUF_NODISCARD ::Protos::SensorData* release_sensor_data();
  ::Protos::SensorData* mutable_sensor_data();
  void set_allocated_sensor_data(::Protos::SensorData* sensor_data);
  private:
  const ::Protos::SensorData& _internal_sensor_data() const;
  ::Protos::SensorData* _internal_mutable_sensor_data();
  public:
  void unsafe_arena_set_allocated_sensor_data(
      ::Protos::SensorData* sensor_data);
  ::Protos::SensorData* unsafe_arena_release_sensor_data();

  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:myservice.PayloadMessage)
 private:
  class _Internal;
  void set_has_sensor_data();

  inline bool has_payload() const;
  inline void clear_has_payload();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::Protos::SensorData* sensor_data_;
    } payload_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_myservice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PayloadMessage

// .Protos.SensorData sensor_data = 1;
inline bool PayloadMessage::_internal_has_sensor_data() const {
  return payload_case() == kSensorData;
}
inline bool PayloadMessage::has_sensor_data() const {
  return _internal_has_sensor_data();
}
inline void PayloadMessage::set_has_sensor_data() {
  _impl_._oneof_case_[0] = kSensorData;
}
inline ::Protos::SensorData* PayloadMessage::release_sensor_data() {
  // @@protoc_insertion_point(field_release:myservice.PayloadMessage.sensor_data)
  if (_internal_has_sensor_data()) {
    clear_has_payload();
    ::Protos::SensorData* temp = _impl_.payload_.sensor_data_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.sensor_data_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Protos::SensorData& PayloadMessage::_internal_sensor_data() const {
  return _internal_has_sensor_data()
      ? *_impl_.payload_.sensor_data_
      : reinterpret_cast< ::Protos::SensorData&>(::Protos::_SensorData_default_instance_);
}
inline const ::Protos::SensorData& PayloadMessage::sensor_data() const {
  // @@protoc_insertion_point(field_get:myservice.PayloadMessage.sensor_data)
  return _internal_sensor_data();
}
inline ::Protos::SensorData* PayloadMessage::unsafe_arena_release_sensor_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:myservice.PayloadMessage.sensor_data)
  if (_internal_has_sensor_data()) {
    clear_has_payload();
    ::Protos::SensorData* temp = _impl_.payload_.sensor_data_;
    _impl_.payload_.sensor_data_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void PayloadMessage::unsafe_arena_set_allocated_sensor_data(::Protos::SensorData* sensor_data) {
  clear_payload();
  if (sensor_data) {
    set_has_sensor_data();
    _impl_.payload_.sensor_data_ = sensor_data;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:myservice.PayloadMessage.sensor_data)
}
inline ::Protos::SensorData* PayloadMessage::_internal_mutable_sensor_data() {
  if (!_internal_has_sensor_data()) {
    clear_payload();
    set_has_sensor_data();
    _impl_.payload_.sensor_data_ = CreateMaybeMessage< ::Protos::SensorData >(GetArenaForAllocation());
  }
  return _impl_.payload_.sensor_data_;
}
inline ::Protos::SensorData* PayloadMessage::mutable_sensor_data() {
  ::Protos::SensorData* _msg = _internal_mutable_sensor_data();
  // @@protoc_insertion_point(field_mutable:myservice.PayloadMessage.sensor_data)
  return _msg;
}

inline bool PayloadMessage::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void PayloadMessage::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline PayloadMessage::PayloadCase PayloadMessage::payload_case() const {
  return PayloadMessage::PayloadCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace myservice

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_myservice_2eproto
