// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: myservice.proto

#include "myservice.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace myservice {
}  // namespace myservice
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_myservice_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_myservice_2eproto = nullptr;
const uint32_t TableStruct_myservice_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_myservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017myservice.proto\022\tmyservice\032\033google/pro"
  "tobuf/empty.proto\032\036google/protobuf/wrapp"
  "ers.proto2U\n\tMyService\022H\n\016StreamMessages"
  "\022\026.google.protobuf.Empty\032\034.google.protob"
  "uf.StringValue0\001b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_myservice_2eproto_deps[2] = {
  &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
  &::descriptor_table_google_2fprotobuf_2fwrappers_2eproto,
};
static ::_pbi::once_flag descriptor_table_myservice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_myservice_2eproto = {
    false, false, 184, descriptor_table_protodef_myservice_2eproto,
    "myservice.proto",
    &descriptor_table_myservice_2eproto_once, descriptor_table_myservice_2eproto_deps, 2, 0,
    schemas, file_default_instances, TableStruct_myservice_2eproto::offsets,
    nullptr, file_level_enum_descriptors_myservice_2eproto,
    file_level_service_descriptors_myservice_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_myservice_2eproto_getter() {
  return &descriptor_table_myservice_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_myservice_2eproto(&descriptor_table_myservice_2eproto);
namespace myservice {

// @@protoc_insertion_point(namespace_scope)
}  // namespace myservice
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
