name: .NET

on:
  push:
    branches: [ "Staging-Environment" ]
  pull_request:
    branches: [ "Staging-Environment" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: 'Source Code/Front-End/UI (WPF)/Smart Pacifier - Tool/Smart Pacifier - Tool'
    - name: Build
      run: dotnet build --no-restore
      working-directory: 'Source Code/Front-End/UI (WPF)/Smart Pacifier - Tool/Smart Pacifier - Tool'
    - name: Run Application
      run: |
        $process = Start-Process -FilePath "Source Code/Front-End/UI (WPF)/Smart Pacifier - Tool/Smart Pacifier - Tool/bin/Debug/net8.0-windows/SmartPacifier.UI (WPF).exe" -NoNewWindow -PassThru -Wait -ErrorAction Stop
        Start-Sleep -Seconds 10
        if ($process.HasExited -eq $false) {
          Stop-Process -Id $process.Id
        }
        if ($process.ExitCode -ne 0) {
          Write-Error "Application exited with code $($process.ExitCode)"
          exit $process.ExitCode
        }
      shell: pwsh
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: 'Source Code/Front-End/UI (WPF)/Smart Pacifier - Tool/Smart Pacifier - Tool'